### PR TITLE
[locales] update from mathjax-i18n for v2.7.0

### LINKED ISSUE #1577: update localizations for v2.7
Just a reminder that we should update the locales.

### PR DESCRIPTION
**Pull request by pkra**
* updates: de, kn, ko, lki, nl, oc, pl, pt-br, pt, zh-hans
* additions: diq

resolves #1577

### CODE REVIEW

**Comment by pkra** [comment]
Sorry about the many trivial changes from updating the header; not sure if there would have been a better way.

**Comment by dpvc** [comment]
I suppose two separate commits, one for the removal of the headers, and one for the actual changes to the content would have made it possible to separate the substantive changes out more easily.  But it is no big deal.

**Comment by dpvc** [comment]
Also, I will be changing the version numbers and copyright dates automatically at the end of the testing process, so there is no need for you to worry about that here.

**Comment by dpvc** [comment]
Does the diq language need to be added to the menu in `MathJax.js`?

**Comment by pkra** [comment]
@dpvc oh! I forgot about that part. I'll make another PR.

**Pull request merged**
