### PR TITLE
Add all macros currently supported by MediaWiki

### PR DESCRIPTION
**Pull request by physikerwelt**
Add all macros definitions that are currently available on
Wikipedia and related projects. Those additional
symbols were introduced in

https://github.com/wikimedia/MathJax/commit/ff2accb8a2dfa5ad03fbd01db52dd1e12c39991e

cf. https://phabricator.wikimedia.org/T105310

### CODE REVIEW

**Comment by physikerwelt** [comment]
@pkra I had a look at the new mathjax-node version. It looks quite promising. However, I discoverd a small difference between the wmf version and the latest MathJax version. Thus I'm creating this pull request to end up with a version of mathjax that can be used to run the [mathpipe](https://github.com/physikerwelt/mathpipe) test and thereafter be the basis for a new mathoid version.

**Comment by pkra** [comment]
Thanks! Have you looked at https://github.com/mathjax/MathJax/issues/566#issuecomment-257555181? That would get you better quality across math styles (in the TeX sense).

**Comment by pkra** [comment]
> Up to now, I'm not aware of any complaints about the spacing of those commands.

Using mathchoice would primarily improve the sizing in display-style (increasing it).

> An other question: How would that interfere with https://phabricator.wikimedia.org/T143520?

It's unrelated.

**Comment by physikerwelt** [comment]
ok. I created a ticket for the size improvements
https://phabricator.wikimedia.org/T161009

**Comment by pkra** [comment]
@physikerwelt ping.

We're wrapping up v2.7.2.

We'd strongly prefer the stretchy construction. Do you have any objections to us fixing it here and then you can pull it back your way?

**Comment by physikerwelt** [comment]
@pkra no. It _seems_ to be all right. We are not bound to a particular MathJax version, so even if there was a bug we could still postpone the update to the new MathJax version until the bug was fixed.

**Comment by pkra** [comment]
Thanks, @physikerwelt.

@dvpc will you make an alternative PR and close this?

**Comment by dpvc** [comment]
@pkra, will do.

**Comment by pkra** [comment]
Thanks!

**Comment by pkra** [comment]
@dpvc cf also https://phabricator.wikimedia.org/T137787

**Comment by dpvc** [comment]
I have made PR #1810 that includes the definitions that handle scaling for displaystyle, and also adds the `\dashint` and `\ddashint` that Peter referenced.  Let me know if this is acceptable.  I'm closing this PR for now.

**Pull request closed without merging**
