### PR TITLE
update locales

### LINKED ISSUE #1821: Update localizations
Cf. mathjax/MathJax-i18n#21

### PR DESCRIPTION
**Pull request by pkra**
Resolves #1821

### CODE REVIEW

**Comment by dpvc** [comment]
I'm OK with this, though I'd have preferred the spacing fixes be done separately.

**Comment by pkra** [comment]
> I'm OK with this, though I'd have preferred the spacing fixes be done separately.

Ugh. Sorry about that! That was automatic and I must have lost the setting to not do this in the mathjax repo. I'll try to make a fix.

**Comment by dpvc** [comment]
No need to change the PR, the removal of extra spaces is fine.  Just hard to see the important changes for this PR among them.

**Comment by pkra** [comment]
Thanks, @dpvc.

**Pull request merged**
