### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by physikerwelt**

### CODE REVIEW

**Comment by pkra** [comment]
Could you please provide some context? Maybe a link to the original tracker?

I think the version number needs to jump to 2.6 to be consistent with our extension versioning. It'd be nice if could you rebase or squash the older commit but that's not critical.

**Comment by physikerwelt** [comment]
@pkra Thank you for your fast reaction.
This refers to https://github.com/mathjax/MathJax/issues/1236
I used the WebUI to create the patch so I'm wondering how ba9afeb5a743249acdea17540b48b14ebc95dbe4 was associated with this request.
It's basically a cherry pick from https://github.com/wikimedia/MathJax/commit/5c58cbe9f77493266c7b122cbe59696c5c7a2b6c.
I'm supposed to make a pull request against develop, right?

**Comment by physikerwelt** [comment]
Closed in favor of #1299

**Comment by pkra** [comment]
> This refers to #1236

Thanks.

> I used the WebUI to create the patch

Weird. Anyway, no problem.

> I'm supposed to make a pull request against develop, right?

Yes, thank you.

**Pull request closed without merging**
