### PR TITLE
Improve position of stretchy accents.  #1735

### PR DESCRIPTION
**Pull request by dpvc**
Only bubble up italic correction or skew for nodes with only one child.

Resolves issue #1735

### CODE REVIEW

**Comment by zorkow** [comment]
I've been playing around with the example from the issue and observe some very bizarre behaviour:
* in HTML-CSS no accent is displayed
* in CommonHTML the enriched math becomes huge
* in SVG it looks good
Maybe we can discuss this tomorrow.

**Comment by dpvc** [comment]
Both issues seem to be related to the `mathsize="36pt"` specification, and have nothing really to do with the issue being addressed here.  I think they should be added as a new issue instead of holding up this one.  (Note that this issue is about horizontal spacing within CHTML only.)

**Comment by dpvc** [comment]
The HTML-CSS issue is due to the way HTML-CSS positions the accents, which fails for large `mathsize` settings.  I've opened #1798 for this.

**Comment by zorkow** [comment]
Sounds good.

**Comment by zorkow** [comment]
CommonHTML problem could be an maction issue. It's independent of accents. I'll file an issue.

**Comment by dpvc** [comment]
I'm working on it already.  It is more than just mactions, it is the collapsible extension itself, somehow.  Just starting to look.

**Comment by zorkow** [comment]
I've filed it in #1800. Feel free to close or move to a11y.

**Comment by dpvc** [comment]
Thanks.  I'm working on it and will figure out if it is a CHTML or an a11y-based problem (or both).  It does seem to only affect CHTML, but that might be just a difference in how CHTML handles `mathsize`.

**Pull request merged**
