### PR TITLE
Remove executable flag of invalid_keypress.ogg (Fixes #2443)

### LINKED ISSUE #2443: Make invalid_keypress.ogg non-executable
### Issue Summary

When working on the Ubuntu package for `libjs-mathjax` (legacy v2.7) we realized there is a potential security risk, because the file `extensions/a11y/invalid_keypress.ogg` is marked as executable file via its UNIX permissions.

### Steps to Reproduce:

1. Clone this repository
2. Checkout the `legacy-v2` branch
3. `ls -la extensions/a11y/invalid_keypress.ogg`
```
-rwxrwxr-x 1 lukas lukas 5353 Mai 22 15:41 extensions/a11y/invalid_keypress.ogg*
```

This audio file does not need to be executable and the `+x` flag should be removed, to avoid the issue where potential attackers would somehow replace it with malicious content.
```
chmod -x extensions/a11y/invalid_keypress.ogg
```

### Technical details:

* MathJax Version: 2.7.4
* Client OS: Ubuntu Linux 20.04

### PR DESCRIPTION
**Pull request by slyon**
### Issue Summary

When working on the Ubuntu package for `libjs-mathjax` (legacy v2.7) we realized there is a potential security risk, because the file `extensions/a11y/invalid_keypress.ogg` is marked as executable file via its UNIX permissions.

### Steps to Reproduce:

1. Clone this repository
2. Checkout the `legacy-v2` branch
3. `ls -la extensions/a11y/invalid_keypress.ogg`
```
-rwxrwxr-x 1 lukas lukas 5353 Mai 22 15:41 extensions/a11y/invalid_keypress.ogg*
```

This audio file does not need to be executable and the `+x` flag should be removed, to avoid the issue where potential attackers would somehow replace it with malicious content.
```
chmod -x extensions/a11y/invalid_keypress.ogg
```

### Technical details:

* MathJax Version: 2.7.4
* Client OS: Ubuntu Linux 20.04

### CODE REVIEW

**Comment by slyon** [comment]
Fixes https://github.com/mathjax/MathJax/issues/2443

**Comment by dpvc** [comment]
Thanks for spotting this issue.

The issue really needs to be fixed in the mathjax/MathJax-a11y repository, which is where the a11y extension development is performed.  These files are copied into the MathJax distribution when a new version is being created.

I will take care of the change in that directory, and that will update the file for the next release.

**Comment by slyon** [comment]
Thanks for taking care of it!

**Comment by dpvc** [comment]
The change has been included in the 2.7.9 release that was made this morning, so I'm closing this PR.

**Pull request closed without merging**
