### PR TITLE
update locales for v2.6

### LINKED ISSUE #1248: Update locales for v2.6

### PR DESCRIPTION
**Pull request by pkra**
Fixes #1248.

### CODE REVIEW

**Comment by pkra** [comment]
Depends on https://github.com/mathjax/MathJax-i18n/pull/11

**Comment by pkra** [comment]
Ready for review.

**Comment by pkra** [comment]
Ooops. I forgot the new languages.

**Comment by dpvc** [comment]
Don't forget that the new locales need to be added to the menu in the `Localization` section of `MathJax.js`.  The menu titles are in the main files of the new locales (the ones with the same name as the locale itself).

**Comment by pkra** [comment]
Ah, I knew I had forgotten to ask about this on the F2F. Will get on it.

**Comment by pkra** [comment]
Updated.

**Pull request merged**
