### PR TITLE
Update for 2.7.1

### PR DESCRIPTION
**Pull request by dpvc**
This is the update to version 2.7.1.  It affects nearly all the files since they copyright and version numbers were updated.  It also includes the `latests.js` file, which allows loading the latest version from cdnjs, rawgit, or jsdelivr (whichever one it was loaded from).  It also includes the accessibility extensions in `extensions/a11y`, and the new mhchem extension in `extensions/TeX/mhchem3`, since these can be loaded automatically by the core MathJax.

I've smoke tested the release using rawgit.com, and all seems well.

### CODE REVIEW

**Comment by pkra** [comment]
Could you update `package.json` to a matching version?

**Comment by dpvc** [comment]
> Could you update `package.json` to a matching version?

Sorry, missed that.  Done.

**Comment by pkra** [comment]
Using your branch via rawgit ([example](https://codepen.io/pkra/pen/qyzpf)), I run into 404s for many SRE json dependencies, in particular breaking the a11y extensions. 

I get fewer (but still some) 404s when loading the `/test` example from localhost.

**Comment by pkra** [comment]
(PS also 404s for the audio files.)

**Comment by pkra** [comment]
It seems `[MathJax`] does not get resolve and appears as a string in the paths, e.g.,

`GET http://localhost:8080/[MathJax]/extensions/a11y/mathmaps/functions/elementary.json 404 (Not Found)`

**Comment by dpvc** [comment]
Yes, I was just looking into that.  Seems to be in the SRE code where it is using the path without resolving it.

I'll have to think about which is the best place to resolve that.

**Comment by pkra** [comment]
Thanks, Davide!

**Comment by dpvc** [comment]
OK, I think the place to fix it is [semantic-enrich line 102](https://github.com/mathjax/MathJax-a11y/blob/master/extensions/semantic-enrich.js#L102), which sets up the SRE path from the a11y path.  If it is changed to

```
  if (!PATH.SRE) PATH.SRE = MathJax.Ajax.fileURL(PATH.a11y);
```

then it will resolve any recursive paths before setting SRE, and so when SRE uses it to build its own paths, that will work out.  If someone sets SRE directly (the `if` check), then they would need to give an explicit path, or use `MathJax.Ajax.fileURL()` to resolve it when it is set, as is done here.

If that seems OK, I'll make an update to a11y.  If so, should that bump the version number of a11y?

**Comment by pkra** [comment]
> If that seems OK, I'll make an update to a11y. 

:+1: 

> If so, should that bump the version number of a11y?

:+1. it's a bug fix, I'd say.

**Comment by zorkow** [comment]
Sorry, whatever went wrong, is my fault. Peter asked me a couple of times
to look at the original PR and while I did have look, I never felt
comfortable to comment as I did not understand fully what was going on. (I
never commented either and I did misjudge the urgency...)

Let me test that first. I'll get back to you shortly.

Best,
Volker

On Mon, Apr 24, 2017 at 5:15 PM, Davide P. Cervone <notifications@github.com

**Comment by zorkow** [comment]
OK, that works for me.
Volker

On Mon, Apr 24, 2017 at 5:15 PM, Davide P. Cervone <notifications@github.com

**Comment by dpvc** [comment]
Thanks.  The issue is that in 2.7.1 the paths can no be nested, as in [a11y] points to [MathJax]/extensions/a11y, but SRE assumed (and rightly so given past experience) that the SRE path was absolute, it didn't take into account the possibility that there was another path being used recursively.

My solution was to make sure the SRE path is fully resolved when it is set.  That way, SRE can use it as it currently does.

I'll make the change in a11y, and then merge the PR immediately (since I'm taking this as the review).  Then I'll update the 2.7.1 branch of MathJax with the updated a11y files.

Davide

**Comment by dpvc** [comment]
OK, I've updated 2.7.1-rc.1, and your example now works for me.  Thanks for catching that.  I had checked the collapsible extension, and thought that that used SRE, but apparently that wasn't enough.

**Comment by pkra** [comment]
Awesome! 

All good from my end.

**Comment by pkra** [comment]
Crap. I still get issue for the two audio files. @dpvc Can you take another look?

**Comment by pkra** [comment]
Looks like https://github.com/mathjax/MathJax-a11y/blob/415ba3cc81f81f85b09e573d42c22be05a64e00f/extensions/explorer.js#L283

**Comment by dpvc** [comment]
That looks right.  I'll make another update.

**Comment by pkra** [comment]
Thanks, Davide!

**Comment by dpvc** [comment]
OK, I've pushed another update.

**Comment by pkra** [comment]
:+1: the smoke has cleared as far as I can tell. 

:shipit:

**Comment by pkra** [comment]
Correction/clarification: "as far as I can tell" => "as far as I'm concerned"

**Comment by dpvc** [comment]
I can do the merge, but will you do whatever is invalid in the release process?  I'm not sure I know what that is any longer.

Also, do you know what we need to do get this to cdnjs?  Does that happen automatically when there is an update to the MathJax master branch, or do we need to make a pull request?

**Comment by pkra** [comment]
> I can do the merge, but will you do whatever is invalid in the release process?

(I'm assuming invalid was autocorrect for needed.)

Yes, I'll tag a release (with release notes) on GitHub; that's all we need now.

> Also, do you know what we need to do get this to cdnjs?

Happens automatically once there's a tag but I'll ping Peter to make sure.

**Pull request merged**
