### PR TITLE
Localize some variables that where accidentally global.  #1806

### PR DESCRIPTION
**Pull request by dpvc**
Localize some variables that where accidentally global in CommonHTML.

 Resolves issue #1806.

### CODE REVIEW

**Comment by TomasRiker** [comment]
Unbelievable coincidence ... I wanted to see whether the `scale` variable did indeed leak into the global object and I found a bug in my own website that also leaked a variable of the same name.
An idea for automated testing of such things: Make a snapshot of all global variables, then load MathJax, display a bunch of different math content, then make a snapshot again and check that there are no new unexpected global variables.

**Comment by dpvc** [comment]
Yes, that is how I found these two (after one was reported in #1806).  The compressor we use reports these variables in some cases (and I thought all cases), but apparently not.  So something like what you suggest would help.  But MathJax consists of 10's of thousands of line of code, and unless you run all of it, you aren't guaranteed to find all global variables.  But it would at least be a step in the right direction.

**Comment by TomasRiker** [comment]
Assuming that the regular tests cover most of MathJax, would it be an option to do the check before/after running all tests in a row, or before/after each individual test?

**Comment by dpvc** [comment]
That is a nice idea, but many of the tests create globals as part of the test, so they would cause problems for this approach.  It would require modifying many of the test files to make that work.

The test framework for version 3 will be entirely rewritten, so we don't expect to put a lot of effort into the current test suite at this point.  Also, version 3 is using Typescript, which will catch these sorts of errors in the development phase.

**Pull request merged**
