### PR TITLE
fix typo in help dialog

### PR DESCRIPTION
**Pull request by christianp**

### CODE REVIEW

**Comment by dpvc** [comment]
Note that this will require a change in the Translate Wiki data files (minor detail)

**Comment by pkra** [comment]
Already fixed on that end  https://github.com/mathjax/MathJax-i18n/blob/master/JSON/en/HelpDialog.json#L11 (but we never import those...)

**Comment by pkra** [comment]
@christianp thanks for merging in that bower fix ;-)

**Comment by christianp** [comment]
GitHub pull requests remain a mystery to me. I have no idea how that commit ended up in this PR.

**Comment by dpvc** [comment]
I'm sorry, but the pull request is still a problem.  It is branched from `master` but should be branched from `develop` (and merged to `develop` as it is now).  The reason the bower fix is included is because it was merged into `master` but not merged into `develop` (as it should have been when the hot-fix was made to `master`).  I merged it into `develop` a few weeks ago, but since your branch is from `master`, it is included in your history here.

The way this is supposed to work is that you make a new branch from the current `develop` branch, make your changes, and then make a pull request to `develop`.  The git-flow model that we are using doesn't allow pulls from `master` into `develop` (only from `develop` into `master`, and then only for new releases).  If this had been a larger set of changes, I'd recommend rebasing the commits onto a new branch from `develop`, but it is probably just easier to make a new branch from `develop` and make the edit again before making a fresh pull request.

Sorry it is so complicated, but once you have done it a couple of times it gets to be more natural.

**Comment by pkra** [comment]
FYI new feature for the web interface is https://github.com/blog/1945-quick-pull-requests

**Pull request closed without merging**
